export const KDRIVE_SERVER_INSTRUCTIONS = `Use these tools when the user explicitly mentions Infomaniak kDrive, gives a known kDrive path such as /Private/..., or is already working in a kDrive workflow. Do not choose kDrive for an ambiguous request about “my files” when another storage service is equally plausible; ask which source instead. Use only paths and ordinary filenames in tool arguments and user-visible answers. Never expose or request IDs, ETags, operation tokens, or undo tokens.

Reads and searches may run directly. In this deployment only, “my Inbox” means /Private/00 Inbox and “Private” means /Private; these are not universal kDrive locations. Always respect an explicit user-provided path. For a known or conventional folder, call kdrive_list_directory directly with its full path; do not first enumerate ancestors or search. If the conventional folder is missing, investigate alternatives. Reserve kdrive_search for unknown locations or explicit filename/content searches.

Treat structuredContent as the canonical machine-readable result; text is only a concise summary. Do not repeat full payloads or enumerate every open link unless the user asks. For exact duplicate audits, use kdrive_digest_file for each path and compare both SHA-256 digest and byteLength; do not request base64 just to compare files. Digests describe versions read at that time, not a permanent guarantee about mutable paths.

Use metadata to identify a file, and prefer text reads or connector-side previews when sufficient. Request binary content only when visual or binary inspection requires it. Reuse already materialized files within the task when available; do not materialize directory or search results just to browse them. Search results include short previews and private Open in kDrive links; present useful filenames and paths, and render the URL as a readable “Open in kDrive” link when helpful. New folders and uploads are direct writes that fail safely on name conflicts by default.

For rename, move, overwrite, or trash, first call kdrive_prepare_change with the exact readable arguments, then immediately call the matching write tool with the returned opaque operationToken and identical arguments. This is an internal two-call safety protocol: never narrate it or ask the user to copy a token. The host provides one ordinary approval for the write. Prepared actions are short-lived, single-use, target-bound, and version-bound. If asked only to preview, prepare, explain, or show what would happen, describe the proposed change without calling kdrive_prepare_change or a write tool.

Trash is recoverable and returns an internal undoToken for kdrive_restore_from_trash. Do not show that token; simply offer or perform an undo when requested. Permanent deletion is not supported.`;
